import { NextRequest, NextResponse } from 'next/server'

interface AuditLog {
  timestamp: string
  type: 'info' | 'warning' | 'error' | 'anomaly'
  message: string
  details?: any
}

interface Anomaly {
  type: 'WORD' | 'EQUATION' | 'CODE' | 'ENTITY' | 'UNKNOWN'
  item: string
  reason: string
  severity: 'low' | 'medium' | 'high'
}

interface AuditReport {
  generated: string
  model: string
  anomalies: Anomaly[]
  total: number
  bufferSize: number
}

export async function POST(request: NextRequest) {
  try {
    const { anomalies, model, bufferSize, systemStatus, customNotes } = await request.json()

    if (!anomalies) {
      return NextResponse.json(
        { error: 'Anomalies data is required' },
        { status: 400 }
      )
    }

    // Generate timestamp
    const generated = new Date().toISOString()

    // Create report content
    const report: AuditReport = {
      generated,
      model: model || 'gemini-2.0-flash-preview-09-2025',
      anomalies,
      total: anomalies.length,
      bufferSize,
      systemStatus: systemStatus || {
        bridgeStatus: 'unknown',
        bufferLength: bufferSize,
        timestamp: new Date().toISOString()
      },
      customNotes
    }

    // Format as plain text
    const content = formatAuditReport(report)

    return NextResponse.json({
      success: true,
      report,
      content,
      filename: `EMG-Audit-${Date.now()}.txt`
    })
  } catch (error) {
    console.error('Audit generation error:', error)
    return NextResponse.json(
      {
        error: 'Failed to generate audit report',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

function formatAuditReport(report: AuditReport): string {
  let content = `EMG SYSTEM AUDIT REPORT
${'='.repeat(60)}
Generated: ${new Date(report.generated).toLocaleString()}
Model: ${report.model}
Buffer Size: ${report.bufferSize} bytes
Anomalies Detected: ${report.total}
${'='.repeat(60)}

`

  // Add anomalies
  if (report.anomalies.length > 0) {
    content += `\nANOMALIES DETECTED:\n`
    content += `${'-'.repeat(60)}\n`
    
    report.anomalies.forEach((anomaly, index) => {
      content += `${index + 1}. [${anomaly.type}] ${anomaly.item}\n`
      content += `   Severity: ${anomaly.severity.toUpperCase()}\n`
      content += `   Reason: ${anomaly.reason}\n\n`
    })
  } else {
    content += `\nANOMALIES DETECTED:\n`
    content += `${'-'.repeat(60)}\n`
    content += `No anomalies detected in current buffer.\n\n`
  }

  // Add system status
  if (report.systemStatus) {
    content += `SYSTEM STATUS:\n`
    content += `${'-'.repeat(60)}\n`
    content += `Bridge Status: ${report.systemStatus.bridgeStatus}\n`
    content += `Buffer Length: ${report.systemStatus.bufferLength} bytes\n`
    content += `Timestamp: ${new Date(report.systemStatus.timestamp).toLocaleString()}\n\n`
  }

  // Add custom notes
  if (report.customNotes && report.customNotes.trim()) {
    content += `CUSTOM NOTES:\n`
    content += `${'-'.repeat(60)}\n`
    content += `${report.customNotes}\n\n`
  }

  content += `${'='.repeat(60)}\n`
  content += `\nReport generated by EMG v9.6 Core Vessel\n`
  content += `Full Stack System - Neural Bridge + Audit System\n`

  return content
}
